name: dataengineering_env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - tensorflow
  - pytorch
  - torchvision
  - torchaudio
  - dask
  - pyspark
  - fastapi
  - uvicorn
  - apache-airflow
  - jupyter
  - jupyterlab
  - pip:
      - mlflow
      - boto3
      - s3fs
